mlflow query tutorial
google/uv-metrics pull request #23
Opened 2020-08-20 23:37 UTC by ajslone

This PR adds a simple mlflow tutorial that demonstrates using UV to log data to mlflow and then how to use the mlflow api to query your results and extract metric data.

2020-08-21 04:26 UTC, sritchie reviewed
Nice work!! Few comments.

2020-08-21 04:26 UTC, sritchie commented on docs/uv/mlflow.rst
> +Please note that this tutorial uses the `matplotlib <https://matplotlib.org>`_ and
maybe make this a `NOTE` with rst syntax?

2020-08-21 04:26 UTC, sritchie commented on docs/uv/mlflow.rst
> +You may also specify the experiment name using the `MLFLOW_EXPERIMENT_NAME`
I think you need double backticks for code. single backticks make italics...

2020-08-21 04:26 UTC, sritchie commented on tutorials/mlflow_queries/tutorial.py
> +  plt.savefig('tutorial.png')
do you want to save it to the actual location that the docs need, so folks could run again to regenerate without moving it?

2020-08-21 17:59 UTC, ajslone commented on tutorials/mlflow_queries/tutorial.py
> +  plt.savefig('tutorial.png')
not sure what would be the correct path for that? Certainly can save somewhere else that's better.

2020-08-21 18:16 UTC, sritchie commented on tutorials/mlflow_queries/tutorial.py
> +  plt.savefig('tutorial.png')
I was thinking have it generate to this location that you used above:

```
.. image:: /_static/img/mlflow_query_tutorial.png
```

assuming these are the same?

2020-08-21 18:19 UTC, ajslone commented on tutorials/mlflow_queries/tutorial.py
> +  plt.savefig('tutorial.png')
Yes, definitely that's the same plot. OK, I see. Assuming that the user runs the tutorial from the source tree, then this will do the right thing.

2020-08-27 21:35 UTC, sritchie requested changes

2020-08-27 21:35 UTC, sritchie commented on docs/uv/mlflow.rst
> +We have a `short tutorial <https://github.com/google/uv-metrics/tree/matser/tutorials/mlflow_queries>`_
whoops, `master` vs `matser`

2020-11-12 17:14 UTC, sritchie commented
Closing in favor of #32

2020-11-12 17:14 UTC, closed without merging